site_name: My Security Docs
site_url: https://vineetpandey.github.io
site_author: you
site_description: Just Sharing!

nav:
  - Home: index.md
  - About: about.md
  - Tutorial:
      - Securing GitLab CI/CD with AWS OIDC: "pages/tutorial/SecuringGitLabCICDwithAWSOIDC/SecuringGitLabCICDwithAWSOIDC.md"
  
theme:
  name: material
  
  palette: 
    primary: green
    scheme: default
    accent: indigo
    
# (Search Plugin and associated features)  
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - search
  - glightbox
  - tags:
      tags_file: tags.md
    


extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js

extra_css:
  - https://use.fontawesome.com/releases/v5.13.0/css/all.css
  - stylesheets/extra.css


# Document title

markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
      
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  
  - pymdownx.smartsymbols
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
  
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vineetiiitalld
      name: Follow me up
    
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/vineetpandeyalld
      name: Let's Connect

    - icon: fontawesome/brands/github
      link: https://github.com/vineetpandey
      name: Check out repos