name: Publish My Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      
      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Deploy 🚀
        run: mkdocs gh-deploy --force --clean --verbose
      
