name: Publish My Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    # running on shared runner
    runs-on: ubuntu-latest
    
    # running on self-hosted runner
    # runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Deploy 🚀
        run: mkdocs gh-deploy --force --clean --verbose
      
